# Generated by Django 5.1.4 on 2025-01-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
